### ISSUE TITLE
Requesting a profile.

### ISSUE THREAD

**Issue by cjemorton** [cbsd/cbsd-vmprofiles#7]
Any chance we could get a proxmox profile for bhyve and cbsd?

https://www.proxmox.com/en/

**Comment by olevole** [comment]
@cjemorton It's not very clear how useful this is. Bhyve hypervisor does not support nested virtualization (that is, you can install Proxmox in Bhyve, but you will not be able to run virtual machines under Proxmox )

**Comment by cjemorton** [comment]
Ok! Good to know!

Did not realize there was no support for nested virtualisation.

Was looking for a way to have a GUI for my VM's. Make things easier to manage and spin up. I've been using cbsd terminal for managing everything for several years. I've tried installing cloneos on freebsd but it has some bugs that's currently not letting it install unfortunately.

**Comment by olevole** [comment]
@cjemorton Please check out https://github.com/cbsd/cbsd-vmprofiles/commit/4e515bc0f8bcfea725344c0037cfbb0c283ccbde

e.g.:

```
fetch -o ~cbsd/etc/vm-linux-Proxmox-8.conf https://raw.githubusercontent.com/cbsd/cbsd-vmprofiles/master/vm-linux-Proxmox-8.conf
```

Unfortunately, in a very short period of my own testing, I discovered a number of issue:

1) the graphical installer did not work in bhyve - please use 'Terminal UI'
2) After installation, I could not enter into UI/WEB as a root user ( Login failed. Please try again,  REALM: Linux PAM.  ) - I do not know what the problem is

PS: BTW, What's the problem with installation of ClonOS ? It is developing slowly (I add new features very rarely due to lack of free time ), but installation from an ISO image should work ( Also, I haven’t tested the installation of clonos scripts on a vanilla FreeBSD for a very long time )

**Comment by cjemorton** [comment]
Thanks for the update.

I'm probably (debating it) going to need to do a whole server rebuild in the near future, and I may be putting ClonOS on the system.
I'm basically running FreeBSD to the bare-metal right now and virtualizing all my services with cbsd in their own jail containers, managing everything with the cbsd command line. I've been doing it this way for several years now.

I've worked my way through all these releases of freebsd, so it's been installed for awhile.
base_amd64_amd64_12.1                   base_amd64_amd64_13.0                   base_amd64_amd64_14.0
base_amd64_amd64_12.2                   base_amd64_amd64_13.1                   FreeBSD-kernel_GENERIC_amd64_12.3
base_amd64_amd64_12.3                   base_amd64_amd64_13.2                   FreeBSD-kernel_GENERIC_amd64_13.1

I was just looking for a way to - 'tack on' a nice GUI, of ClonOS to let me manage more easily from the browser without having to drop to a terminal for basic commands like restarting a jail. 

I could do a full fresh install of ClonOS, but then I'd have to tear down a bunch of stuff and do a full rebuild - and that just makes me nervous, as it's essentially a weeks project because sure as the sun does rise, something will break....

As it is right now, it's "working", minus a few funny boot errors..."scratching my head trying to figure those out"... I was debating moving to XCP-ng as a type 1 hypervisor and then running FreeBSD and it's jails in there, problem is - then I'm injecting Linux code into the stack, at a base layer, and I was trying to avoid that. Case n Point - the current status of CentOS 7 being the underlying OS that XCP-ng is running on, now being discontinued and support dropped.
(Interesting article I was just reading on that: https://xcp-ng.org/blog/2020/12/17/centos-and-xcpng-future/)

The reason I installed FreeBSD to start with was because it wasn't what I consider "fickle" Linux (here today working great, gone tomorrow / bonked like a lemming.) - as I've had problems with Linux in the past over long periods an install becomes really messed up and there is no separation between base and packages, and I can pretty much rely on the release schedule of FreeBSD to no Bork things up - and I know it's going to be around in a few years due to its extremely high install base. 

As a file server, sharing iSCSI and running service jails, I want it as rock solid as possible - Running services in jails is just me using the extra cpu and ram to do something useful besides just providing bulk network storage, and letting it sit idle chugging away.

I was wanting to keep the foundation of the whole stack of tools, BSD based for the underlying stability it's provided. Not just in the code base, but in the project as a whole which the code base is sitting on. 

I was inquiring about running proxmox in bhyve (but since virtualisation can't be passed through, there's no point), for the higher layers of the stack. There's some tools and stacks that are specifically published to run in specific Linux environments - I'd like to try out - without disrupting the lower stable layers of my storage.

Hope that makes sense. (there's probably better ways to do everything)!

**Comment by olevole** [comment]
@cjemorton thanks for your point of view.
ClonOS  is currently designed for use in trusted environments and is currently very limited (it does not do 99% of the capabilities of the CBSD) and is quite far behind in development (low priority). By the way, I’m working on another front-end for bhyve - https://www.youtube.com/watch?v=N9TDelWfDbc (this was mainly necessary due to the fact that I began to prefer to manage virtual machines from a mobile phone rather than a computer ;-). I have a fairly large number of jail containers and virtual machines. They are all controlled via an API (Curl, and I also made an interface to control API via Telegram messenger (trivial tasks: stop/start/create on-demand ).

By the way, I also try to create mixed environments (specifically, I use both Linux and FreeBSD) in my tasks. Sometimes I delegate the same task to both Linux and FreeBSD to keep myself in shape  (+ fight against vendor lock-in ;-). Clearly, the constant variability and inconsistency of Linux is a big problem. At least I can compare ;-).

**Comment by cjemorton** [comment]
Ah! I totally understand! 
I've been doing more and more management of my containers via ssh and my iPhone with a terminal emulator. It's clunky and requires very precise repetitive typing just to execute one start or stop command.

I use telegram too for messaging with family, didn't realize it could do more.

I may be interested in testing out the other front-end at some point, see how things work. It would be nice if it could be accessed via a web page, making it platform independent. I may be wrong, but from the video it looks to be designed to run on android phones only.

Vender lock in is a huge problem - If I get a hint of a project doing that. Time permitting I search for viable alternatives. One example of a huge perverted code base that got so much garbage tacked onto it, its virtually unusable - is FreePBX - something I'm investigating replacing in my home stack as well. 
Problem is, when individuals get a nice polished solution, it seems like the vultures swoop in and try and commercialize it.

Anyways, if you want to chat - I'm over on telegram. - Maybe I can help, and test out some of the features on your front-end for Bhyve give you some feedback from another perspective. Time permitting.
